### ISSUE TITLE
reference error on cypress mailosaur

### ISSUE THREAD

**Issue by mysticdevx** [mailosaur/cypress-mailosaur#25]
Platform: node v14.17.3 on MacOS v11.6, webpack: 5.60.0 cypress v8.3.1

I am working on a project with typescript. We are planning to use Mailosaur. I start implementing but I got a compilation error when I run the script. below is the error message I got:

```
The following error originated from your test code, not from Cypress.

  > Buffer is not defined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
../node_modules/cypress-mailosaur/src/request.js:8:1
   6 |     this.baseUrl = options.baseUrl || 'https://mailosaur.com/';
   7 |     this.apiKey = options.apiKey;
>  8 |     const encodedKey = Buffer.from(`${this.apiKey}:`).toString('base64');
     | ^
   9 |     this.headers = {
  10 |       Accept: 'application/json',
  11 |       Authorization: `Basic ${encodedKey}`, 
View stack trace
 Print to console
    at new Request (webpack://xxxx/../../node_modules/cypress-mailosaur/src/request.js:8:1)
    at MailosaurCommands.mailosaurSetApiKey (webpack://xxxx/../../node_modules/cypress-mailosaur/src/mailosaurCommands.js:39:1)
    at new MailosaurCommands (webpack://xxxx/../../node_modules/cypress-mailosaur/src/mailosaurCommands.js:35:1)
    at register (webpack://xxxx/../../node_modules/cypress-mailosaur/src/register.js:4:1)
    at Object.../../node_modules/cypress-mailosaur/index.js (webpack://xxxx/../../node_modules/cypress-mailosaur/index.js:5:1)
    at __webpack_require__ (webpack://xxxx/webpack/bootstrap:19:1)
    at eval (webpack://xxxx/./cypress/support/index.ts:25:1)
    at eval (https://my_domain.com/__cypress/tests?p=cypress/support/index.ts:154973:4)
    at eval (https://my_domain.com/__cypress/tests?p=cypress/support/index.ts:154975:13)
        at eval (<anonymous>)
From previous event:
    at runScriptsFromUrls (https://my_domain.com/__cypress/runner/cypress_runner.js:164985:98)
    at Object.runScripts (https://my_domain.com/__cypress/runner/cypress_runner.js:164999:11)
    at $Cypress.onSpecWindow (https://wmy_domain.com/__cypress/runner/cypress_runner.js:153977:19)
```

I also tried the mailosaur-node library (with cy.task) in the same project, and again got webpack error, I have opened an issue for that too, see here please: https://github.com/mailosaur/mailosaur-node/issues/49

**Comment by mysticdevx** [comment]
see the referred issue. it is solved by adding Buffer plugin
